eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.29.63:8761/eureka/

#
#spring:
#  web:
#    cors:
#      allowed-origins:
#        - "*"
#      allowed-methods:
#        - GET
#        - POST
#        - PUT
#        - DELETE
#        - OPTIONS
#      allowed-headers:
#        - "*"
#      allow-credentials: true
